### ISSUE TITLE
Crc error

### ISSUE THREAD

**Issue by slusaro2** [kakaki/esphome_dietrich#1]
I'm having crc error in esphome log:

`[22:09:36][D][custom:209]: crc error [22:09:36][D][custom:213]: sample data: 00000000F0A7C64B2D261B00030000000000000000000000F0A7C64B00000000B8312240061DFF3F060A104025068135000000009C67FF3FE0FEFF3F0200000000000000F0A7C64B2F261B003013FF3F`

I've tried both en and pl config files, with same result.
Entities are loaded to HA, but states are unknown.

**Comment by rjblake** [comment]
I had same issue using a nodeMCU. Swapped out with a Adafruit Huzzah (had a spare) and it works without CRC issue. Will do further testing to confirm.

**Comment by MiguelAlbiac** [comment]
Hola. Paso los datos a grafana pero en ocasiones me da lecturas erróneas. Porque puede ser?

**Comment by rjblake** [comment]
@MiguelAlbiac - I don't have much experience with this version (I wrote a PHP version many years ago), but it may be down to the data not being received correctly. I'm not sure if a full CRC is done on all the data received so possibly a cause; although it seems CRC is implemented.

**Comment by slusaro2** [comment]
> I had same issue using a nodeMCU. Swapped out with a Adafruit Huzzah (had a spare) and it works without CRC issue. Will do further testing to confirm.

I have eventually swapped from wemos D1 mini to D1 PRO version and errors are gone too.

**Comment by jghaanstra** [comment]
Exact same issue on a nodemcuv3 board here. Any found a solution already, dont have any other board here right now.

[EDIT]
Changed the pins on my nodemcuv3 and it works now. Here is the new config.

```
uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO15
  rx_pin: GPIO13
  stop_bits: 1
```

**Comment by rjblake** [comment]
> Exact same issue on a nodemcuv3 board here. Any found a solution already, dont have any other board here right now.
> 
> [EDIT]
> Changed the pins on my nodemcuv3 and it works now. Here is the new config.
> 
> ```
> uart:
>   id: uart_bus
>   baud_rate: 9600
>   tx_pin: GPIO15
>   rx_pin: GPIO13
>   stop_bits: 1
> ```

Interesting. Might give that a try. I thought it may be due to the voltage sensitivity (i.e. 5V vs 3.3V) and was going to test with a level shifter (haven't had time till now) to further investigate.

**Comment by kakaki** [comment]
> @MiguelAlbiac - I don't have much experience with this version (I wrote a PHP version many years ago), but it may be down to the data not being received correctly. I'm not sure if a full CRC is done on all the data received so possibly a cause; although it seems CRC is implemented.

Full CRC is not implemented - it's only checking first 3 bytes of header - had some issues with data being and this fixed it.
It's working over 6 month in my house without any issues.

**Comment by Anonymoesje** [comment]
> > Exact same issue on a nodemcuv3 board here. Any found a solution already, dont have any other board here right now.
> > [EDIT]
> > Changed the pins on my nodemcuv3 and it works now. Here is the new config.
> > ```
> > uart:
> >   id: uart_bus
> >   baud_rate: 9600
> >   tx_pin: GPIO15
> >   rx_pin: GPIO13
> >   stop_bits: 1
> > ```
> 
> Interesting. Might give that a try. I thought it may be due to the voltage sensitivity (i.e. 5V vs 3.3V) and was going to test with a level shifter (haven't had time till now) to further investigate.

Did you ever try this out? I'm currently having the same issue with an ESP8266... Also, i'm wondering if the Adafruit Huzzah you had working was directly connected or with a level shifter.
