### ISSUE TITLE
5v from boiler to power the esp? 

### ISSUE THREAD

**Issue by ministryofsillywalks** [kakaki/esphome_dietrich#5]
Sorry if this is a stupid question but does the 5v pin from the boiler supply power to the esp8266?
So theoretically no external power source needed.
Or does the 5v pin expect power input coming from the esp8266?

**Comment by laemen** [comment]
I use the 5v from the boiler to power my esp8266.
My esp8266 requires 3.3v, so I have an interface board in between.
